### ISSUE TITLE
Change sorting participant list

### ISSUE THREAD

**Issue by DanielMartinus** [DanielMartinus/Event-plugin-hangoutsbot#4]
When printing out the participant list it is sorted by GoogleId. This is confusing and creates the habbit of having to generate the agent list each time you want to change something. 

**Sorting right now:**
```python
line 187: enumerate(sorted(participants, key=str)):
```

**Solution**
The list should be sorted based on the time joining the event.

**Comment by PrinterElf** [comment]
I don't see why the list needs to be sorted at all - just iterate it as it appears.
